### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by louis288** [huankoh/CST-GL#4]
Hi, thanks for sharing your excellent work!
I followed instructions to pre-process the SMD data set first. Then I got the following error after running the run.py file (`python run.py --data data/machine-1-1  --expid machine-1-1 --delays [0,1,5,10,20,30,60] --num_nodes 38 --subgraph_size 10 --pca_compo 8`):
![image](https://github.com/huankoh/CST-GL/assets/58628734/16bab647-f0d3-48b9-a1d9-eb203035f2ef)
I don't know what's going on, and I sincerely hope you can give effective guidance, thank you!

**Comment by louis288** [comment]
```
Traceback (most recent call last):
  File "run.py", line 304, in <module>
    pointwise, early = main(i)
  File "run.py", line 140, in main
    tx = trainx[:, :, id, :]
IndexError: tensors used as indices must be long, byte or bool tensors
```

**Comment by baoyixin** [comment]
Hi，have you found the solution?

**Comment by sin-ctrl** [comment]
I've encountered the same issue, do you have any solutions?

**Comment by goodman233** [comment]
run.py line 139   id = torch.tensor(id).type(torch.long).to(device)

**Comment by huankoh** [comment]
Thanks @goodman233 . @All - please feel free to reopen the issue if this is not resolved
